### ISSUE TITLE
[Bug]XLR-11 Engine has no plume

### ISSUE THREAD

**Issue by IAlsoPlayKsp** [KSP-RO/ROEngines#252]
XLR-11 Engine has no plume.
Fresh install of RP-1, followed instructions to the letter.
Create any rocket with the XLR11 engine (mine was an X-Plane) and fire it up. Engine produced thrust and had all features, just no plume. Asking on reddit reveals other people have this problem too. Previous versions had a plume (I last played ~3 months ago, just getting back into it). Bug?

**Comment by Capkirk123** [comment]
I'm not sure what fixing the plume entails, but this probably belongs here

**Comment by IAlsoPlayKsp** [comment]
Not a permanent solution but you can solve it by rolling back waterfall to 0.9.0, so something in the recent versions must've broken it.

**Comment by Capkirk123** [comment]
resolved by https://github.com/post-kerbin-mining-corporation/Waterfall/pull/182

**Comment by IAlsoPlayKsp** [comment]
sorry, this is my first time doing... anything on github besides downloading stuff. how does this now count as resolved?

**Comment by Capkirk123** [comment]
The cause of the issue has been fixed by the linked pull request

**Comment by Gordon-Dry** [comment]
it still has no plume, with CKAN RP-1 Express Install.
So a PR from Jan 03 is still not put in?

**Comment by Capkirk123** [comment]
No, no it is not. Go bug @Jonnyothan if you want it fixed.

**Comment by Capkirk123** [comment]
No, it is not?

**Comment by Gordon-Dry** [comment]
I will try again soon™ but yesterday it was.
